In [ ]:
import numpy as np
import math

In [ ]:
random.seed(9)
x = np.random.rand(2,1)
y = (x[0]**2 + x[1]**2)/2
w = np.  
w = np.random.rand(2,2)
b = np.random.rand(2,1)
print(x)
print(y)
print(w)
print(b)

[[0.37644253]
 [0.10730914]]
[0.07661212]
[[0.64621988 0.17736605]
 [0.92203912 0.23197036]]
[[0.96407384]
 [0.41584303]]


In [ ]:
def sigmoid(x):
  return 1 / (1 + math. exp(-x))

def forward(x,w,b):
  z =np.sum(x * w + b)
  return sigmoid(z) 

def loss(pred,y):
  L = (pred- y)**2
  return L

In [ ]:
# dL/dw = 2x(w*x + b - y) = 2x(pred - y)
def gradient_w(x,y,pred):
  return np.array(2 * x [0]* (pred - y), 2 * x [1]* (pred - y))
# dL/db = 2(w*x + b - y) = 2(pred - y)
def gradient_b(x,y,pred):
  return 2 * (pred - y)

In [ ]:
learning_rate = 0.01
n_iters = 10

In [ ]:
for epoch in range(n_iters):
  # prediction = forward pass
  y_pred = forward(x,w,b)

  # loss
  L = loss(y,y_pred)

  # gradients:
  dw = gradient_w(x,y,y_pred)
  db = gradient_b(x,y,y_pred)

  # update w and b 
  w -= learning_rate * dw
  b -= learning_rate * db

  if epoch % 1 == 0:
    print(f'epoch{epoch + 1}: loss = {L}')
print(f'Predication after training : pred = {forward(x,w,b):.3f}')

epoch1: loss = [0.44241491]
epoch2: loss = [0.42773948]
epoch3: loss = [0.4131774]
epoch4: loss = [0.39876519]
epoch5: loss = [0.38453726]
epoch6: loss = [0.37052562]
epoch7: loss = [0.3567596]
epoch8: loss = [0.3432657]
epoch9: loss = [0.33006747]
epoch10: loss = [0.31718543]
Predication after training : pred = 0.629
