In [1]:
import torch
import random
from collections import OrderedDict
import torchvision
import numpy as np
import math

# Generate input

In [2]:
random.seed(127)
input = torch.randn(1,3,32,32)
input

tensor([[[[-0.0662,  0.5268,  0.5395,  ...,  0.9719,  0.6289,  0.5902],
          [ 0.1667, -0.0998, -0.8983,  ...,  0.3317,  0.6495,  0.3680],
          [-1.0965, -0.9000, -2.1975,  ..., -0.3408, -0.0893,  0.4193],
          ...,
          [ 0.0989, -0.5774, -1.1059,  ..., -0.4656,  0.8693,  0.7781],
          [-1.0299, -0.7237,  0.0807,  ..., -1.6059, -0.3684, -0.1214],
          [-0.5087, -0.8605, -0.9958,  ..., -0.2940,  0.3346,  1.6017]],

         [[ 0.8956, -0.0726,  0.7128,  ...,  1.1203,  0.7472,  0.6594],
          [-1.7178,  0.3152, -0.6435,  ...,  0.2013, -1.6368,  0.7023],
          [ 0.3194,  0.4115, -0.8222,  ..., -1.0655, -1.2694,  0.0892],
          ...,
          [ 1.1426, -0.2912, -0.0294,  ...,  0.2563, -0.2711,  0.4691],
          [-1.1275,  0.3439, -0.0584,  ..., -1.5248,  1.7870, -0.3424],
          [ 0.5836,  0.2167, -1.3560,  ..., -0.3772,  0.6446, -0.7104]],

         [[-0.2822,  1.4276, -0.4466,  ..., -0.1916, -1.0598, -1.0482],
          [-0.5058, -0.4743, -

In [ ]:
def RMSE(t_out,my_out,c,w,h):
  error = 0
  for k in range(c):
    for j in range(w):
      for i in range(h):
        error += np.square(t_out[0][k][i][j] - my_out[k][i][j])
  return np.sqrt(error)

# First page

## Model 1

In [ ]:
# the pytorch model 
m1 = torch.nn.MaxPool2d(kernel_size=2, stride=1, padding=0,
dilation=1, return_indices=False, ceil_mode=False)
output1 = m1(input)
output1.shape

torch.Size([1, 3, 31, 31])

In [ ]:
def M1_script(input):
  # the script of MaxPool2d
  res = []
  for k in range(3): 
    img = np.zeros((31,31))
    for i in range(31):
      for j in range(31):
        temp = np.max(input[0][k][i:i+2,j:j+2])
        img[i][j] = temp
    #   new_img.append(new_row)
    res.append(img)
  return res

In [ ]:
array = np.array(input)
res1 = M1_script(array)

In [ ]:
error1 = RMSE(np.array(output1),res1,3,31,31)
error1

0.0

## Model 2

In [ ]:
# the pytorch model 
m2 = torch.nn.AvgPool2d(kernel_size=2, stride=1, padding=0, 
                                    ceil_mode=False, count_include_pad=True, 
                                    divisor_override=None)
output2 = m2(input)
print(output2.shape)
output2[0][0][0]

torch.Size([1, 3, 31, 31])


tensor([-0.5604, -0.1075, -0.1282,  0.1901,  0.4220,  0.1008,  0.2619,  0.7648,
        -0.1247, -0.6874, -0.3407, -0.1819,  0.0714, -0.0434,  0.0189,  0.5389,
         0.5705,  0.4693,  0.3527,  0.2768, -0.3354, -0.4788, -0.7790, -0.2606,
         0.1202,  0.1616,  0.0631, -0.4901, -0.0208, -0.1059,  0.0977])

In [ ]:
def M2_script(input):
  # the script of AvgPool2d
  res = []
  for k in range(3): 
    img = np.zeros((31,31))
    for i in range(31):
      for j in range(31):
        temp = np.mean(input[0][k][i:i+2,j:j+2])
        img[i][j] = temp
    #   new_img.append(new_row)
    res.append(img)
  return res

In [ ]:
res2 = M2_script(array)
res2[0][0]

array([-0.56041723, -0.10750734, -0.12817606,  0.19005522,  0.42203525,
        0.10082519,  0.26189581,  0.76480162, -0.12474355, -0.68742669,
       -0.34068647, -0.18188938,  0.07135148, -0.04344792,  0.01889145,
        0.53888869,  0.5704897 ,  0.46925774,  0.35274857,  0.27680242,
       -0.33539334, -0.47883061, -0.77901703, -0.26064014,  0.12018158,
        0.16156997,  0.06311099, -0.49007162, -0.02075627, -0.1059294 ,
        0.09769592])

In [ ]:
error2 = RMSE(np.array(output2),res2,3,31,31)
error2

0.0

## Model 3

In [ ]:
# the pytorch model 
m3 = torch.nn.Conv2d(in_channels=3, out_channels=6,kernel_size=3, stride=1,
                     padding=0, dilation=1, groups=1, bias=True, 
                     padding_mode='zeros')

In [ ]:
m3.weight.data.fill_(0.01)
m3.bias.data.fill_(0.02)
output3 = m3(input)
print(output3.shape)
output3[0][0][0]

torch.Size([1, 6, 30, 30])


tensor([-0.0259,  0.0761,  0.0313,  0.1048,  0.0323,  0.0951,  0.0485,  0.1090,
         0.0567,  0.0301, -0.0039,  0.0189, -0.0183,  0.0187, -0.0066,  0.0777,
         0.0440,  0.0901,  0.0193,  0.0094,  0.0265, -0.0055,  0.0319, -0.0174,
         0.0746,  0.0208,  0.0552,  0.0104,  0.0680,  0.0407],
       grad_fn=<SelectBackward>)

In [ ]:
def M3_script(input,w,b):
# The script of Conv2d kernel_size=3, dilation=1
  res = []
  for k in range(6): 
    img = np.zeros((30,30))
    for i in range(30):
      for j in range(30):
        temp = []
        for g in range(3):
          temp.append(input[0][g][i:i+3,j:j+3] * w)
        img[i][j] = np.sum(temp) + b
    #   new_img.append(new_row)
    res.append(img)
  return res

In [ ]:
res3 = M3_script(array,0.01,0.02)
res3[0][0]

array([-0.025907  ,  0.07605052,  0.03125939,  0.10478688,  0.03231597,
        0.09511822,  0.04849885,  0.10904535,  0.05674535,  0.03013325,
       -0.00389215,  0.01887149, -0.01826572,  0.01871268, -0.00660858,
        0.07766109,  0.0440018 ,  0.09006143,  0.01931454,  0.00936575,
        0.02652792, -0.00548301,  0.03187105, -0.01735724,  0.07459883,
        0.02076983,  0.05518575,  0.01038799,  0.06801023,  0.04065682])

In [ ]:
out3 = output3.cpu().detach().numpy()
error3 = RMSE(out3,res3,6,30,30)
error3

4.496224235982009e-07

## Model 4

In [ ]:
m4 = torch.nn.Conv2d(in_channels=3, out_channels=6,
kernel_size=5, stride=2, padding=0, dilation=2, groups=1,
bias=True, padding_mode='zeros')

In [ ]:
m4.weight.data.fill_(0.01)
m4.bias.data.fill_(0.02)
output4 = m4(input)
print(output4.shape)
output4[0][0][0]

torch.Size([1, 6, 12, 12])


tensor([ 0.0086,  0.0502, -0.0116,  0.0436, -0.0218, -0.0331, -0.0082,  0.0654,
         0.0549,  0.1437,  0.1927,  0.1713], grad_fn=<SelectBackward>)

In [ ]:
# since the  dilation=2, we should bulid a new wight with size 9
w4 = np.zeros((9,9))
for i in range(0,9,2):
  for j in range(0,9,2):
    w4[i][j] = 0.01
w4


array([[0.01, 0.  , 0.01, 0.  , 0.01, 0.  , 0.01, 0.  , 0.01],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.01, 0.  , 0.01, 0.  , 0.01, 0.  , 0.01, 0.  , 0.01],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.01, 0.  , 0.01, 0.  , 0.01, 0.  , 0.01, 0.  , 0.01],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.01, 0.  , 0.01, 0.  , 0.01, 0.  , 0.01, 0.  , 0.01],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.01, 0.  , 0.01, 0.  , 0.01, 0.  , 0.01, 0.  , 0.01]])

In [ ]:
def M4_script(input,w,b):
  # the script of Conv2d kernel_size=5, dilation=2
  res = []
  for k in range(6): 
    img = np.zeros((12,12))
    for i in range(0,24,2):
      # 24 = 32 - 9 + 1 
      for j in range(0,24,2):
        temp = []
        for g in range(3):
          temp.append(input[0][g][i:i+9,j:j+9] * w)
        img[i//2][j//2] = np.sum(temp) + b
    res.append(img)
  return res

In [ ]:
res4 = M4_script(array,w4,0.02)
res4[0][0]

array([ 0.00855295,  0.05020118, -0.01162511,  0.04358543, -0.021835  ,
       -0.0331358 , -0.00815958,  0.06539241,  0.05491396,  0.1437312 ,
        0.19265763,  0.17129957])

In [ ]:
error3 = RMSE(output4,res4,6,12,12)
error3

3.3014146947114005e-07

## Model 5

In [ ]:
m5 = torch.nn.ConvTranspose2d(in_channels=3, out_channels=4,
kernel_size=3, stride=1, padding=0, output_padding=0,
groups=1, bias=True, dilation=1, padding_mode='zeros')

In [ ]:
m5.weight.data.fill_(0.01)
m5.bias.data.fill_(0.02)
output5 = m5(input)
print(output5.shape)
output5[0][0]

torch.Size([1, 4, 34, 34])


tensor([[-0.0083,  0.0059,  0.0059,  ...,  0.0317,  0.0124,  0.0148],
        [-0.0223, -0.0064, -0.0224,  ...,  0.0557,  0.0451,  0.0284],
        [-0.0407, -0.0232, -0.0259,  ...,  0.0407,  0.0515,  0.0217],
        ...,
        [ 0.0482,  0.0118,  0.0193,  ...,  0.0287, -0.0062,  0.0214],
        [ 0.0415,  0.0045, -0.0013,  ...,  0.0199, -0.0147,  0.0198],
        [ 0.0420,  0.0251,  0.0265,  ...,  0.0029, -0.0185,  0.0039]],
       grad_fn=<SelectBackward>)

In [ ]:
# build new input by adding interpolation
# 36 = 32 +2+2 each side add 2 * 0
inputT = []
for k in range(3):
  tempT= np.zeros((36,36))  
  for i in range(2,34):
    for j in range(2,34):
      tempT[i][j] = array[0][k][i - 2][j - 2]
  inputT.append(tempT)
inputT = np.array(inputT)
inputT.shape

(3, 36, 36)

In [ ]:
def M5_script(input,w,b):
  # the script of ConvTranspose2d
  res = []
  for k in range(4): 
    img = np.zeros((34,34))
    for i in range(34):
      for j in range(34):
        temp = []
        for g in range(3):
          temp.append(input[g][i:i+3,j:j+3] * w)
        img[i][j] = np.sum(temp) + b
    res.append(img)
  return np.array(res)

In [ ]:
res5 = M5_script(inputT,0.01,0.02)
res5[0][0]

array([-0.00834702,  0.00591917,  0.00593034,  0.03271648,  0.01853428,
        0.04513393,  0.06553582,  0.08721901,  0.06947413,  0.05855929,
        0.02814739,  0.02489543, -0.01065321,  0.01104944, -0.02179958,
        0.03220751,  0.00403493,  0.04068441,  0.01327718,  0.02704545,
        0.02749056,  0.03489428,  0.06121208,  0.00888699,  0.01123571,
       -0.0194839 ,  0.05234765,  0.04103027,  0.04930419,  0.03925565,
        0.03943456,  0.03173258,  0.01241508,  0.01482373])

In [ ]:
out5 = output5.cpu().detach().numpy()
error5 = RMSE(out5,res5,4,34,34)
error5

2.5423003690167885e-07

#Second page

##Model 6

In [ ]:
output6 = torch.flatten(input, start_dim=0, end_dim=-1)
print(output6.shape)
output6

torch.Size([3072])


tensor([-1.6298,  0.6396, -0.5472,  ...,  0.0807, -0.0957, -0.8763])

In [ ]:
def M6_script(array):
  # the script of flatten
  res = []
  for k in range(3):
    for i in range(32):
      for j in range(32):
        res.append(array[0][k][i][j])
  return np.array(res)
res6 = M6_script(array)
print(res6.shape)
res6 

(3072,)


array([-1.6298413 ,  0.63964784, -0.5472226 , ...,  0.08069441,
       -0.09567828, -0.8763014 ], dtype=float32)

In [ ]:
def RMSE6(t_out,my_out,n):
  error = 0
  for i in range(n):
    error += np.square(t_out[i] - my_out[i])
  return np.sqrt(error)

In [ ]:
out6 = output6.cpu().detach().numpy()
error5 = RMSE6(out6,res6,3072)
error5

0.0

## Model 7

In [ ]:
output7 = torch.sigmoid(input,out=None)
print(output7.shape)
output7[0][0][0]

torch.Size([1, 3, 32, 32])


tensor([0.1639, 0.6547, 0.3665, 0.3857, 0.6155, 0.6776, 0.7530, 0.8542, 0.7240,
        0.6014, 0.2479, 0.4840, 0.4849, 0.7901, 0.3487, 0.6927, 0.3314, 0.6170,
        0.4447, 0.7458, 0.7249, 0.2846, 0.7504, 0.4071, 0.6372, 0.2200, 0.7354,
        0.3561, 0.5091, 0.4223, 0.4210, 0.6998])

In [ ]:
def sigmoid(x):
  # sigmoid function
  return 1 / (1 + math. exp(-x))
def M7_script(array):
  res = []
  for k in range(3):
    temp = np.zeros((32,32))
    for i in range(32):
      for j in range(32):
        temp[i][j] = sigmoid(array[0][k][i][j])
    res.append(temp)
  return np.array(res)
res7 = M7_script(array)
print(res7.shape)
res7[0][0] 

(3, 32, 32)


array([0.1638521 , 0.65467385, 0.36650902, 0.38568981, 0.61551092,
       0.67759834, 0.75300484, 0.85419014, 0.72399779, 0.60138138,
       0.24786309, 0.48396389, 0.48487302, 0.79005049, 0.34873877,
       0.69270123, 0.33142552, 0.61703423, 0.44474867, 0.7458114 ,
       0.72489079, 0.28461057, 0.75042433, 0.40705442, 0.63719936,
       0.21998145, 0.73544185, 0.35605823, 0.50909255, 0.42233098,
       0.42103865, 0.69976382])

In [ ]:
out7 = output7.cpu().detach().numpy()
error7 = RMSE(out7,res7,3,32,32)
error7

1.1555854912187194e-06

## Model 8

In [ ]:
rois_in_feature = torch.Tensor([[0, 5.0231, 6.0234, 15.1564, 19.6561]])  #取4位小数
roi_start_w = 5
roi_start_h = 6
roi_end_w = 15
roi_end_h = 20

roi_width = (roi_end_w - roi_start_w + 1)
roi_height = (roi_end_h - roi_start_h + 1)

bin_size_w = roi_width / 3
bin_size_h = roi_height / 3

In [ ]:
m8 = torchvision.ops.roi_pool(input, rois_in_feature,output_size=(3, 3))
print(m8.shape)
m8[0][0]

torch.Size([1, 3, 3, 3])


tensor([[1.7590, 2.5338, 1.8760],
        [1.8031, 2.6782, 1.8412],
        [1.6808, 2.2893, 1.8962]])

In [ ]:
# the script of ROI pooling
res8 = []
for j in range(3):
    sub_res = []
    for i in range(3):
        sub_res.append(input[..., int(6+bin_size_h*(j)):math.ceil(6+bin_size_h*(j+1)), int(5+bin_size_w*(i)):math.ceil(5+bin_size_w*(i+1))][0][0].max())
    res8.append(sub_res)
res8

[[tensor(1.7590), tensor(2.5338), tensor(1.8760)],
 [tensor(1.8031), tensor(2.6782), tensor(1.8412)],
 [tensor(1.6808), tensor(2.2893), tensor(1.8962)]]

In [ ]:
def RMSE8(t_out,my_out,c,w,h):
  error = 0
  for k in range(1):
    for j in range(w):
      for i in range(h):
        error += np.square(t_out[0][k][i][j] - my_out[i][j])
  return np.sqrt(error)

In [ ]:
error8 = RMSE8(m8,res8,3,3,3)
error8

tensor(0.)

## Model 9

In [ ]:
running_mean = torch.zeros(3) + 1
running_var = torch.ones(3) * 2
m9 = torch.nn.functional.batch_norm(input, running_mean, running_var,
weight=None, bias=None, training=False, momentum=0.1,
eps=1e-05)
print(m9.shape)
m9[0][0]

torch.Size([1, 3, 32, 32])


tensor([[-1.8596, -0.2548, -1.0940,  ..., -0.9286, -0.9323, -0.1088],
        [-1.6276, -0.6715, -1.1122,  ..., -0.2818, -0.9853, -0.5257],
        [-1.4257, -0.7150, -0.2403,  ..., -0.7328,  0.3231,  0.0165],
        ...,
        [ 0.3318, -0.8083, -0.1066,  ..., -0.4747, -1.2321, -0.5108],
        [-1.7105, -1.5052, -0.7598,  ..., -0.0919, -1.9464,  0.1522],
        [-0.4635, -0.9716, -0.4122,  ..., -0.3265, -2.0441, -0.6720]])

In [ ]:
def M9_script(array,mean,var,eps):
  # The script of batch_norm
  res = []
  for k in range(3):
    img = np.zeros((32,32))
    for i in range(32):
      for j in range(32):
        img[i][j] = (array[0][k][i][j] - mean)/ np.sqrt(var + eps)
    res.append(img)
  return res

In [ ]:
array = np.array(input)
res9 = M9_script(array,1,2,1e-05)
res9[0]

array([[-1.85957399, -0.25480682, -1.09404887, ..., -0.9285786 ,
        -0.93232581, -0.10877151],
       [-1.62764737, -0.67148708, -1.11215321, ..., -0.28184429,
        -0.9852842 , -0.52571344],
       [-1.42571297, -0.71501901, -0.2402597 , ..., -0.73275968,
         0.32309036,  0.0164916 ],
       ...,
       [ 0.33183496, -0.80833885, -0.10664841, ..., -0.47471548,
        -1.23206849, -0.5107705 ],
       [-1.71045881, -1.505218  , -0.75977913, ..., -0.09194839,
        -1.94644761,  0.15217731],
       [-0.46348059, -0.97159732, -0.41223654, ..., -0.32646218,
        -2.04409867, -0.67196843]])

In [ ]:
out9 = m9.cpu().detach().numpy()
error9 = RMSE(out9,res9,3,32,32)
error9

2.8989378585758513e-06

##Model 10

In [53]:
random.seed(128)
input10 = torch.FloatTensor(3,32,32).uniform_(0,1)
target = torch.randint(0,3, (3,32,))
# target= target.type(torch.LongTensor)

In [30]:
array10 = np.array(input10)
array10[2]

array([[0.07785201, 0.25821805, 0.60242313, ..., 0.7303437 , 0.29609632,
        0.10219741],
       [0.37144697, 0.81550455, 0.61697096, ..., 0.6135922 , 0.9873885 ,
        0.69450676],
       [0.9050689 , 0.61334574, 0.32565093, ..., 0.07359326, 0.5310299 ,
        0.04006654],
       ...,
       [0.59780174, 0.27778727, 0.3109001 , ..., 0.30358863, 0.62489045,
        0.08473581],
       [0.86480725, 0.9172278 , 0.6139338 , ..., 0.31119424, 0.81177133,
        0.66187507],
       [0.96256286, 0.55362916, 0.7128168 , ..., 0.7798468 , 0.32170558,
        0.7789511 ]], dtype=float32)

In [44]:
import math
def M10_script(array,target):
  # The script of cross_entropy
  res= []
  for k in range(3):
    img = np.zeros((32,32))
    for i in range(32):
      for j in range(32):
        temp = -1 * math.log(np.exp(input[target[k,i],i,j]) / np.exp(input[:,i,j]).sum())    
  return np.mean(res)

In [ ]:
res10 = M10_script(array10,target)

In [54]:
m10 = torch.nn.functional.cross_entropy(input10, target, weight=None,
size_average=None, ignore_index=-100, reduce=None,
reduction='mean')
m10

tensor(3.5121)

In [57]:
RMSE = m10 - res10
RMSE

tensor(0.)

## Model 11

In [ ]:
target = torch.randn(1,3,32,32)

In [ ]:
m11 = torch.nn.functional.mse_loss(input, target, size_average=None,
reduce=None, reduction='mean')
m11

tensor(2.0276)

In [ ]:
def M11_script(array,target):
  # The script of MSE
  L = []
  for k in range(3):
    for i in range(32):
      for j in range(32):
        L.append(np.square(array[0][k][i][j] - target[0][k][i][j]))
  return np.mean(L)

In [ ]:
targ = np.array(target)
res11 = M11_script(array,targ)
res11

2.0275514

In [ ]:
error11 = np.array(m11) - res11
error11

2.3841858e-07